export const buttonTime = document.querySelector('#buttonTime')
export const buttonLetter = document.querySelector('#buttonLetter')
export const buttonMusic = document.querySelector('#buttonMusic')
export const buttonQuejas = document.querySelector('#buttonQuejas')
export const buttonSingIn = document.querySelector('#buttonSingIn')
export const buttonFullScreen = document.querySelector('#buttonFullScreen')


export const sectionScreenLoding = document.querySelector('#sectionScreenLoding')
export const sectionSingIn = document.querySelector('#sectionSingIn')
export const sectionTime = document.querySelector('#sectionTime')
export const sectionLetter = document.querySelector('#sectionLetter')
export const sectionMusic = document.querySelector('#sectionMusic')
export const sectionQuejas = document.querySelector('#sectionQuejas')
export const conteinerMeses = document.querySelector('#meses')
export const conteinerDias = document.querySelector('#dias')
export const conteinerHoras = document.querySelector('#horas')
export const conteinerMinutos = document.querySelector('#minutos')
export const conteinerSegundos = document.querySelector('#segundos')
export const profileHeader = document.querySelector('#profileHeader')
export const profileSingIn = document.querySelector('#profileSingIn')
export const nav = document.querySelector('.nav')

export const inputName = document.querySelector('#inputName')
export const password = document.querySelector('#password')
export const confirmPassword = document.querySelector('#confirmPassword')
